### ISSUE TITLE
Build on .NET6 is not supported anymore

### ISSUE THREAD

**Issue by oe-rene-kortmann** [SteveDunn/Vogen#865]
### Describe the bug

I have a project which is still targeting `.NET 6.0`. The build pipeline only have .NET 6.0 installed.

If i update to Vogan `>= 7.0.1` i cannot build anymore because:

```
Projects using Vogen cannot build using MSBuild '17.3.4'. MSBuild '17.4.0' or later is required.
```

The NuGet information for Vogan describes, that it supports `.NETStandard2.0` so i would expect that building projects which targets `.NET 6.0` should be working, too.

### Steps to reproduce

I added an example .NET 6.0 project here, which shows the error.
It contains a `global.json` File to force `.NET6` as used SDK.

```json
{
  "sdk": {
    "version": "6.0.0",
    "rollForward": "feature"
  }
}
```

[VoganNet6.zip](https://github.com/user-attachments/files/24055576/VoganNet6.zip)

### Expected behaviour

I can build the project in `.NET 6.0` again.

**Comment by SteveDunn** [comment]
Oh no! Sorry about that. I'll take a look. 
Thanks for the bug report.

**Comment by SteveDunn** [comment]
I think I've fixed it - I'll get a new pre-release version out shortly. Would you mind verifying it works?

**Comment by oe-rene-kortmann** [comment]
Thanks for the reply. 

Sorry for the late answer, i was on vacation.

I tested `8.0.5-beta.1` and now it builds but the source generators are not executed.
No code is generated and so the methods on the `struct / class` are not there.

I updated the example by adding a custom id type.

[VoganNet6_with_id.zip](https://github.com/user-attachments/files/24431272/VoganNet6_with_id.zip)


```
error CS0117: 'MyId' does not contain a definition for 'Parse' [/Users/rene.kortmann/dev/playground/VoganExample/VoganNet6/VoganNet6.csproj]
```

If i use a higher `.NET` version, it works. But not if i build with .NET 6.
